version: '3.8'

services:
  # Application Node.js
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://moroccan_user:moroccan_pass@db:5432/moroccan_marketplace
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-production
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: moroccan_marketplace
      POSTGRES_USER: moroccan_user
      POSTGRES_PASSWORD: moroccan_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis pour le cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Adminer pour la gestion de la base de données (optionnel)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: